baseURL = "https://klbminhlong.github.io/"
languageCode = "vi-vn"
defaultContentLanguage = "vi"
title = "Nguyễn Minh Long - Network Programming Blog"
theme = "PaperMod"

[pagination]
  pagerSize = 10
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

[params]
  description = "Blog cá nhân chia sẻ về Lập trình mạng, Java & JavaScript của Nguyễn Minh Long."
  author = "Nguyễn Minh Long"
  defaultTheme = "dark"          # auto / light / dark (ưu tiên Dark mode)
  disableThemeToggle = false

  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true

  hideSummary = false

  [params.assets]
    disableHLJS = false
    favicon = "/favicon.ico"

  [params.label]
    text = "Nguyễn Minh Long - Network Programming Blog"
    icon = "/images/icon.jpg"      # đặt file tại static/images/icon.jpg
    iconHeight = 48

  # SEO & Social
  [params.social]
    GitHub = "KLBMinhLong"
    Email = "nguyenminhlongcntt@gmail.com"
    Facebook = "https://www.facebook.com/long.nguyen.601773/"
    LinkedIn = "www.linkedin.com/in/minh-long-nguyễn-09984a333"

  # Open Graph & Twitter Cards
  images = ["/images/profile/GrayscaleVersion.png"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang chủ"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "blog"
    name = "Bài viết"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "Về tôi"
    url = "/about/"
    weight = 30

  [[menu.main]]
    identifier = "categories"
    name = "Danh mục"
    url = "/tags/"
    weight = 40

  [[menu.main]]
    identifier = "contact"
    name = "Liên hệ"
    url = "/contact/"
    weight = 50

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    noClasses = false
    style = "monokai"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


