baseURL = "https://klbminhlong.github.io/"
languageCode = "vi-vn"
defaultContentLanguage = "vi"
title = "Nguyễn Minh Long - Network Programming Blog"
theme = "PaperMod"

[pagination]
  pagerSize = 10
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

[params]
  description = "Blog cá nhân chia sẻ về Lập trình mạng, Java & JavaScript của Nguyễn Minh Long."
  author = "Nguyễn Minh Long"
  defaultTheme = "auto"          # auto / light / dark
  disableThemeToggle = false

  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true

  hideSummary = false

  [params.assets]
    disableHLJS = false
    favicon = "/favicon.ico"

  [params.homeInfoParams]
    Title = "Nguyễn Minh Long"
    Content = """
Sinh viên năm 4 HUTECH.  
Chia sẻ kiến thức về **Lập trình mạng**, **Java** và **JavaScript**.

Blog này được xây dựng với Hugo + PaperMod, theo phong cách **tối giản trắng/đen/xám**.
"""

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    noClasses = false
    style = "monokai"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


